---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-logging-operator
  namespace: openshift-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cluster-logging-operator
  template:
    metadata:
      labels:
        name: cluster-logging-operator
    spec:
      serviceAccountName: cluster-logging-operator
      containers:
      - name: cluster-logging-operator
        image: quay.io/openshift/origin-cluster-logging-operator:latest
        imagePullPolicy: IfNotPresent
        command:
        - cluster-logging-operator
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: OPERATOR_NAME
            value: "cluster-logging-operator"
          - name: ELASTICSEARCH_IMAGE
            value: "quay.io/openshift/origin-logging-elasticsearch5:latest"
          - name: FLUENTD_IMAGE
            value: "quay.io/openshift/origin-logging-fluentd:latest"
          - name: KIBANA_IMAGE
            value: "quay.io/openshift/origin-logging-kibana5:latest"
          - name: CURATOR_IMAGE
            value: "quay.io/openshift/origin-logging-curator5:latest"
          - name: OAUTH_PROXY_IMAGE
            value: "quay.io/openshift/origin-oauth-proxy:latest"
          - name: RSYSLOG_IMAGE
            value: "quay.io/viaq/rsyslog:latest"
