# vim: set ft=ansible

- name: get current machinesets
  shell: "oc get machineset -o name -n openshift-machine-api | awk -F/ '{print $2}'"
  register: machinesets_list

- name: create machine autoscaler for each machineset
  k8s:
    state: present
    definition:
      apiVersion: "autoscaling.openshift.io/v1alpha1"
      kind: MachineAutoscaler
      metadata: 
       name: "autoscale-{{ item }}"
       namespace: "openshift-machine-api"
      spec: 
       minReplicas: 1
       maxReplicas: 4
       scaleTargetRef: 
        apiVersion: "machine.openshift.io/v1beta1"
        kind: MachineSet
        name: "{{ item }}"
  with_items: "{{ machinesets_list.stdout_lines }}"

- name: create the cluster autoscaler
  k8s:
    state: present
    definition:
      apiVersion: "autoscaling.openshift.io/v1alpha1"
      kind: "ClusterAutoscaler"
      metadata:
        name: "default"
      spec:
        resourceLimits:
          maxNodesTotal: 20
        scaleDown:
          enabled: true
          delayAfterAdd: 10s
          delayAfterDelete: 10s
          delayAfterFailure: 10s
