
# Force dep to vendor the code generators, which aren't imported just used at dev time.
# Picking a subpackage with Go code won't be necessary once https://github.com/golang/dep/pull/1545 is merged.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
]

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  branch = "v0.0.7"

[[constraint]]
  name = "github.com/openshift/elasticsearch-operator"
  branch = "master"

[[constraint]]
  name = "github.com/openshift/api"
  branch = "master"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  revision = "5fd1e9e9fac5261e9ad9d47c375afc014fc31d21"
