apiVersion: v1
kind: "Template"
metadata:
  name: cluster-logging-dev-build-template
  annotations:
    description: "Template for creating local builds of logging components from source."
    tags: "infrastructure"
labels:
  logging-infra: development
  provider: openshift
  component: development
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: origin-cluster-logging-operator
    name: origin-cluster-logging-operator
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: cluster-logging-operator
    name: cluster-logging-operator
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: origin-cluster-logging-operator:latest
    resources: {}
    source:
      git:
        uri: ${CL_OP_GITHUB_URL}
        ref: ${CL_OP_GITHUB_BRANCH}
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
      type: Docker
parameters:
-
  description: 'URL for cluster-logging-operator fork'
  name: CL_OP_GITHUB_URL
  value: https://github.com/openshift/cluster-logging-operator
-
  description: 'branch for cluster-logging-operator fork'
  name: CL_OP_GITHUB_BRANCH
  value: master
